### PR TITLE
Create new repo: zenoh-plugin-ros2dds

### PR DESCRIPTION
**Pull request by JEnoch**

### CODE REVIEW

**Comment by netomi** [comment]
Can some project lead or fellow committer approve this request?

**Comment by JEnoch** [comment]
I'm committer for Eclipse Zenoh and I approve it ! 😃

**Review by netomi — APPROVED** [review]

**Comment by netomi** [comment]
repo has been created.

**Comment by JEnoch** [comment]
@netomi : It seems I don't have "write access" to the created repo.
In https://github.com/eclipse-zenoh/zenoh-plugin-ros2dds/pull/1, I can't merge and see:
> Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.

Did I miss something in my changes in `otterdog/eclipse-zenoh.jsonnet` ?

**Comment by netomi** [comment]
it takes up to 2h for the sync script to set the permissions for newly created repos. You can fork it and already prepare a PR. Once the permissions are set you will be able to merge.

**Pull request merged**
