### PR TITLE
revert: Rename default eclipse-zenoh/zenoh branch to `main_old`

### PR DESCRIPTION
**Pull request by fuzzypixelz**
This reverts commit 4ce6bf3b2b895fcd98b35ef18b03e34de86a60f9.

See #10.

### CODE REVIEW

**Comment by netomi** [comment]
I guess you renamed the branch to be able to circumvent the ruleset to be able to force push to the branch.
However in this case it would have been better to temporarily disable the ruleset which is supported by rulesets.

See https://otterdog.readthedocs.io/en/latest/reference/organization/repository/ruleset/ property enforcement.

**Review by kydos — APPROVED** [review]
approved.

**Comment by fuzzypixelz** [comment]
> I guess you renamed the branch to be able to circumvent the ruleset to be able to force push to the branch. However in this case it would have been better to temporarily disable the ruleset which is supported by rulesets.

I agree. But I also wanted to avoid any destructive operations "just in case" :) But good to know about the ruleset enforcement status!

**Comment by netomi** [comment]
just to double check because that looks a bit weird to me:

image

so the main_old branch is now quite some commits ahead of the main branch though only 1 commit should have been reverted? Is this expected?

**Comment by fuzzypixelz** [comment]
> just to double check because that looks a bit weird to me:
> 
> image
> 
> so the main_old branch is now quite some commits ahead of the main branch though only 1 commit should have been reverted? Is this expected?

@netomi Oh that's because the commit merged the `protocol_changes` branch into `main`, and `protocol_changes` has long history (it's a development branch). Here's a comparison of `protocol_changes` and `main_old`: https://github.com/eclipse-zenoh/zenoh/compare/protocol_changes...main_old (notice how they're almost the same save for the revert commit).

Thanks for the double-check though! I was also worried about this at first :)

**Comment by netomi** [comment]
ah ok ty for checking, the commit history as displayed by github does not correctly account for that then.

**Pull request merged**
