### PR TITLE
Add org token for zenoh bot

### PR DESCRIPTION
**Pull request by heurtematte**
Related to: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4113

### CODE REVIEW

**Review by kydos — APPROVED** [review]
Looks good. Thanks.

**Comment by heurtematte** [comment]
Modification is live!

**Comment by heyong4725** [comment]
The solution looks good, thank you very much!

**Review by heyong4725 — COMMENTED** [review]
The solution looks good. Thanks

**Pull request merged**
