### PR TITLE
Update Otterdog configuration

### PR DESCRIPTION
**Pull request by fuzzypixelz**
This pull request includes 5 changes:

1. Remove the `PAT` secret as it is unused and will be replaced by `BOT_TOKEN_WORKFLOW`.
2. Extend auto-merge to all repos. This was enabled in the past, but not everywhere.
3. Change the default branch from `master` to `main` where applicable. We have created `main` branches up-to-date with `master` and will refrain from merging pull requests on `master` in the meantime.
4. Change the default branch name for new repositories, so that we we don't accidentally create repos with a default branch name of `master` in the future, ensuring a uniform branch name under eclipse-zenoh.
5. Enable the "Require status checks" branch protection rule for select repos. This change is limited in scope due to the difficulty of specifying status checks on GitHub.

### CODE REVIEW

**Comment by netomi** [comment]
the default branch name is already specified in the default as "main", so there is no need to specify it explicitly, you can remove the property default_branch.

Also the logic to change the default branch is the same as when doing it via the Web UI:

- if a branch with that name exists, use that as default
- if no branch exists, rename the current default branch to the new name

so you dont have create main branches yourself, but changing the default branch to the new name, everything would be done automatically. As you have already done so, its ok, just for your information for the future.

**Comment by netomi** [comment]
for status checks to enable, you have to wrap them into a branch protection rule like that:

```
branch_protection_rules+: [
  orgs.newBranchProtectionRule('main') {
    required_approving_count: 0,
    required_status_checks+: ["ci"]
  }
]
```

be aware if you add something like that, you will not be able to push directly to the branch as you require the ci status check which will only be attached when making a PR. If this is ok with you we can go ahead.

If some people still should be able to push to the branch without a PR, we need to add bypasser.

**Comment by fuzzypixelz** [comment]
@netomi Thanks for the quick reply!

> you can remove the property default_branch.

Just to make sure, you mean to remove the `default_branch_name` property from the organization settings, correct?

> so you dont have create main branches yourself

Ah. Thanks for information. This would've saved a lot of time and trouble :)

> be aware if you add something like that, you will not be able to push directly to the branch as you require the ci status check which will only be attached when making a PR

I must've misunderstood how branch protection rules work then. Because I haven't enabled `requires_pull_request`, so I assumed that `requires_status_checks` would only affect the ability to merge pull requests, not push commits on `main` branch directly.

Regardless, I think it's a good idea to have a set of bypassers for special circumstances. Is it possible to include all committers? The docs suggest something like `@eclipse-zenoh/committers`, but I'm not sure if this slug needs to be defined somewhere first.

**Comment by fuzzypixelz** [comment]
It would seem that the `committers` slug is defined by Eclipse itself and not GitHub: https://projects.eclipse.org/content/committer, in addition to `project-lead` and `mentor-1`.

**Comment by netomi** [comment]
> @netomi Thanks for the quick reply!
> 
> > you can remove the property default_branch.
> 
> Just to make sure, you mean to remove the `default_branch_name` property from the organization settings, correct?

yes.

> > be aware if you add something like that, you will not be able to push directly to the branch as you require the ci status check which will only be attached when making a PR
> 
> I must've misunderstood how branch protection rules work then. Because I haven't enabled `requires_pull_request`, so I assumed that `requires_status_checks` would only affect the ability to merge pull requests, not push commits on `main` branch directly.

thats what I also assumed, but we did setup branch protection rules like that for other projects and learned then that the status checks are always enforced regardless if a pull request is created or not.

> Regardless, I think it's a good idea to have a set of bypassers for special circumstances. Is it possible to include all committers? The docs suggest something like `@eclipse-zenoh/committers`, but I'm not sure if this slug needs to be defined somewhere first.

no problem.

I will update the PR to address that. I will need to convert the branch protection rule to a ruleset though due to that reason:

https://stackoverflow.com/questions/71669640/bypass-required-status-checks-in-github

**Comment by netomi** [comment]
I updated the configuration to convert the branch protection rules to rulesets and introduced a custom template to avoid duplicating the same config.

btw. you can use the playground at https://eclipse-zenoh.github.io/.eclipsefdn/playground/ to test out snippets and see the final configuration taking into account the default configuration.

**Comment by netomi** [comment]
if you agree on that changes we can merge and apply them.

btw. I also enable internal and public packages on org level, which should be set by default for each project and it was set to false till now.

**Comment by fuzzypixelz** [comment]
@netomi Thanks! I wasn't aware of the playground, very useful.

Don't we also need to set `requires_status_checks: true`? The docs state that `required_status_checks` are "Only taken into account when `requires_status_checks` is enabled". Otherwise, let's request the review.

**Comment by netomi** [comment]
> @netomi Thanks! I wasn't aware of the playground, very useful.
> 
> Don't we also need to set `requires_status_checks: true`? The docs state that `required_status_checks` are "Only taken into account when `requires_status_checks` is enabled". Otherwise, let's request the review.

Take a look at the diff view:

image

its already enabled in the default config, so no need to explicitly set it to true. You only need to change things that differ from the default.

**Review by netomi — APPROVED** [review]

**Comment by netomi** [comment]
changes are live, was the biggest change we ever applied at once:

image

**Pull request merged**
