### PR TITLE
fix: Update zenoh-* repos to allow squash merges

### PR DESCRIPTION
**Pull request by diogomatsubara**
Reviewers are encouraged to keep a cleaner git history before merging.

### CODE REVIEW

**Comment by netomi** [comment]
Is the intent of this PR to clean up the config?

**Comment by diogomatsubara** [comment]
> Is the intent of this PR to clean up the config?

No, to enable the squash merge as an option to reviewers so they can keep cleaner history on those repositories

**Comment by netomi** [comment]
Squash merge is already enabled in the default as such your change does not have an effect afaict

**Comment by netomi** [comment]
you can see the full settings also in the dashboard: https://otterdog.eclipse.org/projects/iot.zenoh/repos/homebrew-zenoh#settings

here you can see for example that for the homebrew-zenoh repo the settings is already enabled, as it is inherited from the default settings.

**Comment by diogomatsubara** [comment]
@netomi I thought I had to set it explicit. Sorry for then noise

**Pull request closed without merging**
